### ISSUE TITLE
Repetitive functions

### ISSUE THREAD

**Issue by pablomayobre** [insweater/gamejoltlua#12]
The `GJ.pingSession()` function has only two valid forms:

```
http://gamejolt.com/api/game/v1/sessions/open/?status=active&game_id=GAMEID&format=dump&username=USERNAME&user_token=USERTOKEN&signature=SIGNATURE

http://gamejolt.com/api/game/v1/sessions/open/?status=idle&game_id=GAMEID&format=dump&username=USERNAME&user_token=USERTOKEN&signature=SIGNATURE
```

and the `GJ.closeSession()` function has got just one:

```
http://gamejolt.com/api/game/v1/sessions/close/?&game_id=GAMEID&format=dump&username=USERNAME&user_token=USERTOKEN&signature=SIGNATURE
```

I think that once the user calls `GJ.openSession()` we could already generate the signatures for this two functions.

I'm suggesting this because pingSession is done once every 30 seconds and that means calculating the hash 120 times in an hour, which I think is pointless

**Comment by mbrovko** [comment]
Sounds great. Will look into this later today.

**Comment by mbrovko** [comment]
Tested both versions.

No cache:
![gjnocache](https://cloud.githubusercontent.com/assets/4989165/6439479/1a969402-c0e4-11e4-9be0-c065946cbd32.png)

With cache:
![gjwithcache](https://cloud.githubusercontent.com/assets/4989165/6439459/ea9b4126-c0e3-11e4-9ae1-954f15d0bcf9.png)

Well, I don't know. Difference isn't that huge.

**Comment by pablomayobre** [comment]
Hahaha pointless!! Let's leave it like that

**Comment by ghost** [comment]
Shouldn't this issue be closed as "won't fix" since it was determined pointless?

**Comment by pablomayobre** [comment]
I'll close it!
