### ISSUE TITLE
Is http.lua required?

### ISSUE THREAD

**Issue by josefnpat** [insweater/gamejoltlua#2]
Can't this just be a dependency, instead of included in the repo?

Love supplies `socket.http` and works just fine without it.

**Comment by pablomayobre** [comment]
As josefnpat says, `socket.http` is already in [LÖVE source code](https://bitbucket.org/rude/love/src/e0d0ba859cb7b45392a26abf22a992665f510d6e/src/libraries/luasocket/libluasocket/http.lua?at=default) and in many other [Lua distributions](https://code.google.com/p/luaforwindows/).

It comes [bundled with the LuaSockets](https://github.com/diegonehab/luasocket/blob/master/src/http.lua) library, which already is a requirement for this lib
